start cmd /d /c "main.py 1 && timeout -1"
start cmd /d /c "main.py 2 && timeout -1"
start cmd /d /c "main.py 3 && timeout -1"
start cmd /d /c "main.py 4 && timeout -1"
start cmd /d /c "main.py 5 && timeout -1"